// Extract the app's exact WORKER_CODE voxelizer from tinyworld-app.tsx and emit
// a runnable module (voxelizer.mjs) that uses local `three` instead of esm.sh.
// This guarantees the offline test voxelizes a GLB byte-for-byte the way the
// live browser worker does — no hand-maintained copy to drift.
import { readFileSync, writeFileSync } from "node:fs";

// The LIVE staging debug scan (?debugWorld=1) voxelizes through tw-staging-core's
// WORKER_CODE — extract from there so offline == live. (Was tinyworld-app.tsx,
// a different/older worker that lacked the staging wall/floor/ceiling passes.)
const SRC = process.env.TW_APP ?? "/__substrate/space/src/tw-staging-core.tsx";
const OUT = new URL("./voxelizer.mjs", import.meta.url).pathname;
const app = readFileSync(SRC, "utf8");

const marker = "const WORKER_CODE = String.raw`";
const start = app.indexOf(marker);
if (start < 0) throw new Error("WORKER_CODE not found in " + SRC);
const bodyStart = start + marker.length;
const end = app.indexOf("`;", bodyStart);
if (end < 0) throw new Error("WORKER_CODE close not found");
let body = app.slice(bodyStart, end);

// Read the injected constants straight from the app so they never drift.
const constOf = (name: string, dflt: string) => {
  const m = app.match(new RegExp(`const ${name} = ([0-9_.]+)`));
  return m ? m[1].replace(/_/g, "") : dflt;
};
const subs: Record<string, string> = {
  "${THREE_URL}": "IGNORED",
  "${GLTF_URL}": "IGNORED",
  "${MAX_TRIANGLES}": constOf("MAX_TRIANGLES", "500000"),
  "${VOXEL_METERS}": constOf("VOXEL_METERS", "0.015"),
  "${MAX_WATER}": constOf("MAX_WATER", "10"),
  "${TERRAIN_DEPTH}": constOf("TERRAIN_DEPTH", "5"),
};
for (const [k, v] of Object.entries(subs)) body = body.split(k).join(v);

body = body
  .replace("const THREE = await import('IGNORED');", "const THREE = await import('three');")
  .replace(
    "const { GLTFLoader } = await import('IGNORED');",
    "const { GLTFLoader } = await import('three/examples/jsm/loaders/GLTFLoader.js');",
  );

writeFileSync(
  OUT,
  `// AUTO-GENERATED by extract-voxelizer.ts — do not edit; re-run to refresh.
export async function voxelize(buffer, weather) {
  const messages = [];
  const self = { postMessage: (m) => messages.push(m) };
  ${body}
  await self.onmessage({ data: { buffer, weather } });
  return messages[messages.length - 1];
}
`,
);
console.log("wrote voxelizer.mjs from", SRC);
