// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { Database } from "bun:sqlite";
import { mkdirSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { spawn, spawnSync } from "node:child_process";

const DATA_DIR = "/home/workspace/project-tinyworld/data";
const DB_PATH = `${DATA_DIR}/tinyworld.db`;
const TMP_BASE = "/tmp/tinyworld-infer";
const KEYFRAMES = 8;
const GEMINI_MODEL = "gemini-2.5-flash";
const GEMINI_ENDPOINT = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;

// Geometric (depth + RGB-D odometry + TSDF) inference path.
// Slow (~20s CPU on a 30s capture) but produces real room geometry.
const PYTHON_BIN = "/usr/local/bin/python3.12";
const V2V_SCRIPT = "/home/workspace/project-tinyworld/tools/video_to_voxels.py";
const OLD_PATH_SCRIPT = "/home/workspace/project-tinyworld/tools/old_path_from_capture.py";
const OLD_PATH_PYTHON = "/home/workspace/project-tinyworld/.venv-oldpath/bin/python";
// Merge-at-most pipeline: joint COLMAP co-registration gate + non-destructive
// union merge. Replace is banned; GPS only nominates, geometry decides.
const MERGE_SCRIPT = "/home/workspace/project-tinyworld/tools/merge_capture_into_world.py";

const SCENE_PROMPT = `You are looking at keyframes from a 30-second video walkthrough of a physical space.

Your job is to describe this space as a structured "scene" that a stylized voxel-world generator will use to build a small floating island that captures the FEEL of the room — not its exact geometry. This is intentionally lossy; emphasize mood, palette, and a handful of memorable features over architectural precision.

Constraints:
- Pick the room_type that best matches the dominant function of the space.
- Pick a light mood that matches the overall illumination across the frames.
- Pick a scale: "tight" (small room), "medium" (normal room), "open" (large room or outdoor).
- aspect_ratio: 0.4 (long & narrow), 1.0 (square), 2.5 (very wide). Use 1.0 if unsure.
- palette: 3-5 hex colors sampled from dominant surfaces (walls, floor, large objects).
- vibe_tags: 3-6 short evocative tags (e.g. "soft morning", "industrial", "plant-filled", "minimal").
- features: 4-10 memorable objects. For each, set:
    - kind from the enum.
    - x, z in -1..1 (floor coords, 0,0 is room center).
    - wall: which side of the room the object is against ("north","south","east","west") or "center" for things in the middle (rugs, coffee tables, plants on the floor). Doors and windows MUST have a wall side.
    - size: "small" / "medium" / "large".
- name: 2-4 word name that captures the place.

Return ONLY the JSON object matching the schema.`;

const SCENE_SCHEMA = {
  type: "object",
  properties: {
    room_type: {
      type: "string",
      enum: ["bedroom", "living_room", "kitchen", "bathroom", "hallway", "office", "studio", "outdoor", "other"],
    },
    light: { type: "string", enum: ["warm", "cool", "dim", "bright", "daylight", "night"] },
    scale: { type: "string", enum: ["tight", "medium", "open"] },
    aspect_ratio: { type: "number" },
    palette: { type: "array", items: { type: "string" }, minItems: 2, maxItems: 5 },
    vibe_tags: { type: "array", items: { type: "string" }, minItems: 2, maxItems: 8 },
    features: {
      type: "array",
      minItems: 0,
      maxItems: 12,
      items: {
        type: "object",
        properties: {
          kind: {
            type: "string",
            enum: ["seat", "table", "plant", "screen", "lamp", "bed", "shelf", "door", "window", "appliance", "decor", "structure"],
          },
          description: { type: "string" },
          x: { type: "number" },
          z: { type: "number" },
          wall: { type: "string", enum: ["north", "south", "east", "west", "center"] },
          size: { type: "string", enum: ["small", "medium", "large"] },
        },
        required: ["kind", "x", "z", "wall", "size"],
      },
    },
    name: { type: "string" },
  },
  required: ["room_type", "light", "scale", "aspect_ratio", "palette", "vibe_tags", "features", "name"],
};

function getDb() {
  mkdirSync(DATA_DIR, { recursive: true });
  const db = new Database(DB_PATH);
  db.run(`CREATE TABLE IF NOT EXISTS worlds (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    lat REAL NOT NULL,
    lon REAL NOT NULL,
    owner TEXT DEFAULT 'kj',
    base_blocks INTEGER DEFAULT 0,
    integrity REAL DEFAULT 100,
    created_at INTEGER NOT NULL,
    last_visited INTEGER NOT NULL,
    last_scanned INTEGER NOT NULL
  )`);
  db.run(`CREATE TABLE IF NOT EXISTS world_blocks (
    world_id TEXT PRIMARY KEY,
    payload TEXT NOT NULL,
    block_count INTEGER DEFAULT 0,
    resolution INTEGER DEFAULT 0,
    updated_at INTEGER NOT NULL
  )`);
  db.run(`CREATE TABLE IF NOT EXISTS world_zones (
    world_id TEXT NOT NULL,
    zone_index INTEGER NOT NULL,
    kind TEXT,
    payload TEXT NOT NULL,
    block_count INTEGER DEFAULT 0,
    t_start REAL,
    t_end REAL,
    created_at INTEGER NOT NULL,
    PRIMARY KEY (world_id, zone_index)
  )`);
  db.run(`CREATE TABLE IF NOT EXISTS pending_captures (
    id TEXT PRIMARY KEY,
    lat REAL NOT NULL,
    lon REAL NOT NULL,
    owner TEXT NOT NULL,
    name TEXT,
    duration_ms INTEGER NOT NULL,
    bytes INTEGER NOT NULL,
    mime TEXT,
    video_path TEXT NOT NULL,
    captured_at INTEGER NOT NULL,
    status TEXT DEFAULT 'pending',
    gate_status TEXT,
    gate_reason TEXT
  )`);
  // Best-effort migration: add columns if upgrading from older schema.
  try { db.run(`ALTER TABLE pending_captures ADD COLUMN world_id TEXT`); } catch {}
  try { db.run(`ALTER TABLE pending_captures ADD COLUMN scene_json TEXT`); } catch {}
  try { db.run(`ALTER TABLE pending_captures ADD COLUMN inferred_at INTEGER`); } catch {}
  try { db.run(`ALTER TABLE pending_captures ADD COLUMN imu_path TEXT`); } catch {}
  try { db.run(`ALTER TABLE pending_captures ADD COLUMN imu_samples INTEGER DEFAULT 0`); } catch {}
  try { db.run(`ALTER TABLE pending_captures ADD COLUMN error_msg TEXT`); } catch {}
  try { db.run(`ALTER TABLE pending_captures ADD COLUMN inference_started_at INTEGER`); } catch {}
  try { db.run(`ALTER TABLE pending_captures ADD COLUMN merge_candidate_world_id TEXT`); } catch {}
  try { db.run(`ALTER TABLE pending_captures ADD COLUMN merge_decision TEXT`); } catch {}
  return db;
}

// ---------------------------------------------------------------------------
// Worker liveness. Async inference runs as fire-and-forget promises inside
// THIS server process — a deploy restart kills them mid-flight, leaving rows
// stuck at status='inferring' forever, while the old "already inferring"
// check swallowed every retry POST. Track live workers in-process and, at
// module load, sweep any 'inferring' row whose worker cannot exist anymore.
// ---------------------------------------------------------------------------
const liveWorkers = new Set<string>();
const INFER_TIMEOUT_MS = 45 * 60 * 1000;

// ---------------------------------------------------------------------------
// Done/fail Telegram notification. The pipeline runs 10-30 min, so instead of
// babysitting the capture page, KJ gets a Telegram ping when a scan reaches a
// terminal state. Delivery rides a child Zo session via the /zo/ask API
// (ZO_CLIENT_IDENTITY_TOKEN is in this server's env). Best-effort:
// notification failures never affect the scan result.
// ---------------------------------------------------------------------------
async function notifyScanResult(r: {
  ok: boolean;
  captureId: string;
  worldId?: string;
  worldName?: string;
  blockCount?: number;
  merged?: boolean;
  elapsedMs: number;
  error?: string;
}) {
  try {
    const token = process.env.ZO_CLIENT_IDENTITY_TOKEN;
    if (!token) {
      console.log("[notify] no ZO_CLIENT_IDENTITY_TOKEN — skipping scan notification");
      return;
    }
    const mins = Math.max(1, Math.round(r.elapsedMs / 60000));
    const text = r.ok
      ? `TinyWorld scan done: ${r.worldName || r.worldId || r.captureId}\n` +
        `${(r.blockCount ?? 0).toLocaleString("en-US")} blocks · ${mins} min · ` +
        (r.merged ? "merged into existing world" : "new world") +
        (r.worldId ? `\nhttps://kj.zo.space/tinyworld-staging?world=${encodeURIComponent(r.worldId)}` : "")
      : `TinyWorld scan FAILED after ${mins} min (capture ${r.captureId})\n` +
        `${(r.error || "unknown error").slice(0, 300)}\n` +
        `Reopen the capture page and hit RETRY PROCESSING.`;
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 120000);
    try {
      const resp = await fetch("https://api.zo.computer/zo/ask", {
        method: "POST",
        headers: { authorization: token, "content-type": "application/json" },
        body: JSON.stringify({
          input:
            "Use the send_telegram_message tool to send KJ a Telegram message containing EXACTLY this text, nothing added or removed:\n\n" +
            text,
          model_name: "byok:9b3c7f89-93cc-4477-8962-67a2c0e4b6ae",
        }),
        signal: controller.signal,
      });
      console.log(`[notify] ${r.captureId} ${r.ok ? "done" : "failed"} → zo/ask status ${resp.status}`);
    } finally {
      clearTimeout(timer);
    }
  } catch (e: any) {
    console.error("[notify] scan notification failed:", e?.message || e);
  }
}

function sweepOrphanedInferring() {
  try {
    const db = getDb();
    try {
      const rows: any[] = db.query(`SELECT id, world_id FROM pending_captures WHERE status = 'inferring'`).all();
      for (const row of rows) {
        if (liveWorkers.has(row.id)) continue;
        const block: any = row.world_id
          ? db.query(`SELECT block_count FROM world_blocks WHERE world_id = ?`).get(row.world_id)
          : null;
        if (block && Number(block.block_count || 0) > 0) {
          // The python pipeline writes blocks itself; if blocks landed but the
          // Bun worker died before stamping status, the scan actually succeeded.
          const now = Date.now();
          db.run(`UPDATE pending_captures SET status = 'processed', inferred_at = ? WHERE id = ?`, [now, row.id]);
          db.run(`UPDATE worlds SET base_blocks = ?, last_scanned = ? WHERE id = ?`, [Number(block.block_count), now, row.world_id]);
          console.log(`[infer] boot sweep: ${row.id} already had saved blocks — marked processed`);
        } else {
          db.run(
            `UPDATE pending_captures SET status = 'failed', error_msg = ? WHERE id = ?`,
            ["inference interrupted by a server restart — tap retry to reprocess this capture", row.id],
          );
          console.log(`[infer] boot sweep: ${row.id} orphaned in 'inferring' — marked failed (retryable)`);
        }
      }
    } finally {
      db.close();
    }
  } catch (e) {
    console.error("[infer] boot sweep failed:", e);
  }
}
sweepOrphanedInferring();

function fnv1a(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function mulberry32(seed: number) {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function extractKeyframes(videoPath: string, durationMs: number, outDir: string): string[] {
  mkdirSync(outDir, { recursive: true });
  const seconds = Math.max(2, durationMs / 1000);
  // fps filter: KEYFRAMES frames spread evenly across the clip.
  const fps = (KEYFRAMES / seconds).toFixed(4);
  const args = [
    "-y",
    "-loglevel", "error",
    "-i", videoPath,
    "-vf", `fps=${fps},scale=512:-2`,
    "-frames:v", String(KEYFRAMES),
    "-q:v", "4",
    `${outDir}/f_%02d.jpg`,
  ];
  const res = spawnSync("ffmpeg", args, { stdio: "pipe" });
  if (res.status !== 0) {
    throw new Error(`ffmpeg failed (${res.status}): ${res.stderr?.toString().slice(0, 300)}`);
  }
  const files = readdirSync(outDir).filter((n) => n.endsWith(".jpg")).sort();
  if (files.length === 0) throw new Error("ffmpeg produced no keyframes");
  return files.map((n) => readFileSync(`${outDir}/${n}`).toString("base64"));
}

async function callGemini(apiKey: string, frames: string[]): Promise<any> {
  const parts: any[] = [{ text: SCENE_PROMPT }];
  for (const data of frames) parts.push({ inline_data: { mime_type: "image/jpeg", data } });
  const req = {
    contents: [{ role: "user", parts }],
    generationConfig: {
      responseMimeType: "application/json",
      responseSchema: SCENE_SCHEMA,
      temperature: 0.6,
      maxOutputTokens: 4096,
      thinkingConfig: { thinkingBudget: 0 },
    },
  };
  const res = await fetch(`${GEMINI_ENDPOINT}?key=${apiKey}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(req),
  });
  if (!res.ok) {
    const txt = await res.text();
    throw new Error(`Gemini ${res.status}: ${txt.slice(0, 300)}`);
  }
  const data = await res.json();
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) {
    const finish = data?.candidates?.[0]?.finishReason || "unknown";
    throw new Error(`Empty Gemini response (finish=${finish})`);
  }
  try {
    return JSON.parse(text);
  } catch (e) {
    throw new Error(`Gemini returned invalid JSON (${text.length} chars, head: ${text.slice(0, 200)})`);
  }
}

const FLOOR_BY_TYPE: Record<string, [string, string]> = {
  bedroom: ["grass", "dirt"],
  living_room: ["dryGrass", "dirt"],
  kitchen: ["stone", "dirt"],
  bathroom: ["snow", "stone"],
  hallway: ["dirt", "stone"],
  office: ["stone", "dirt"],
  studio: ["dirt", "stone"],
  outdoor: ["grass", "dirt"],
  other: ["dirt", "grass"],
};

const FEATURE_LAYER: Record<string, string> = {
  seat: "dirt",
  table: "stone",
  plant: "leaves",
  screen: "metal",
  lamp: "fruit",
  bed: "dryGrass",
  shelf: "stone",
  door: "stone",
  window: "snow",
  appliance: "metal",
  decor: "fruit",
  structure: "stone",
};

const SCALE_SPAN: Record<string, number> = { tight: 50, medium: 70, open: 100 };

// Pick a warmth-biased floor override from the scene palette.
// Returns null if no strong signal; otherwise [top, base].
function paletteFloor(palette: string[]): [string, string] | null {
  if (!Array.isArray(palette) || palette.length === 0) return null;
  let warm = 0, cool = 0, green = 0, bright = 0;
  for (const hex of palette) {
    const m = /^#?([0-9a-f]{6})$/i.exec(String(hex).trim());
    if (!m) continue;
    const r = parseInt(m[1].slice(0, 2), 16);
    const g = parseInt(m[1].slice(2, 4), 16);
    const b = parseInt(m[1].slice(4, 6), 16);
    if (r > b + 25) warm++;
    if (b > r + 25) cool++;
    if (g > r + 15 && g > b + 15) green++;
    if (r + g + b > 600) bright++;
  }
  if (green >= 2) return ["grass", "dirt"];
  if (cool >= 2 && bright >= 1) return ["snow", "stone"];
  if (cool >= 2) return ["stone", "dirt"];
  if (warm >= 2) return ["dryGrass", "dirt"];
  return null;
}

type WallSide = "north" | "south" | "east" | "west" | "center";

function generateLayers(scene: any, seedStr: string) {
  const rand = mulberry32(fnv1a(seedStr));
  const span = SCALE_SPAN[scene.scale] || 70;
  const aspect = Math.max(0.4, Math.min(2.5, Number(scene.aspect_ratio) || 1));
  // Rectangular floor whose long axis is X. Total cells ~ span*span but stretched.
  const halfX = Math.max(20, Math.floor((span / 2) * Math.sqrt(aspect)));
  const halfZ = Math.max(20, Math.floor((span / 2) / Math.sqrt(aspect)));

  const [paletteTop, paletteBase] = paletteFloor(scene.palette) || FLOOR_BY_TYPE[scene.room_type] || FLOOR_BY_TYPE.other;
  const topLayer = paletteTop;
  const baseLayer = paletteBase;

  const buckets: Record<string, number[]> = {};
  const occupied = new Set<string>();
  const push = (layer: string, x: number, y: number, z: number) => {
    const key = `${x},${y},${z}`;
    if (occupied.has(key)) return;
    occupied.add(key);
    if (!buckets[layer]) buckets[layer] = [];
    buckets[layer].push(x, y, z);
  };
  const isOccupied = (x: number, y: number, z: number) => occupied.has(`${x},${y},${z}`);

  // Rectangular floor with slightly noisy corners so it doesn't feel CAD-perfect.
  const cornerBite = Math.max(2, Math.min(halfX, halfZ) / 8);
  const inFloor = (dx: number, dz: number) => {
    if (Math.abs(dx) > halfX || Math.abs(dz) > halfZ) return false;
    // Round off corners by removing cells in a quarter-circle larger than (halfX - bite, halfZ - bite).
    const cx = Math.abs(dx) - (halfX - cornerBite);
    const cz = Math.abs(dz) - (halfZ - cornerBite);
    if (cx > 0 && cz > 0 && (cx * cx + cz * cz) > cornerBite * cornerBite) return false;
    return true;
  };

  for (let dx = -halfX; dx <= halfX; dx++) {
    for (let dz = -halfZ; dz <= halfZ; dz++) {
      if (!inFloor(dx, dz)) continue;
      push("stone", dx, 0, dz);
      push(baseLayer, dx, 1, dz);
      if (rand() < 0.96) push(topLayer, dx, 2, dz);
    }
  }

  // Walls: collect door/window openings first so we can cut holes in the right walls.
  const features = Array.isArray(scene.features) ? scene.features : [];
  type Opening = { wall: WallSide; tParam: number; widthCells: number; bottomY: number; topY: number };
  const openings: Opening[] = [];
  const wallHTotal = scene.scale === "tight" ? 5 : scene.scale === "open" ? 3 : 4;
  for (const f of features) {
    if (f.kind !== "door" && f.kind !== "window") continue;
    const wall: WallSide = (f.wall as WallSide) || "north";
    if (wall === "center") continue;
    // tParam: position along the wall, derived from the perpendicular coord.
    const t =
      wall === "north" || wall === "south"
        ? Math.max(-1, Math.min(1, Number(f.x) || 0))
        : Math.max(-1, Math.min(1, Number(f.z) || 0));
    const widthCells = f.kind === "door" ? 3 : 2;
    const bottomY = f.kind === "door" ? 3 : 3 + Math.floor(wallHTotal * 0.4);
    const topY = f.kind === "door" ? 3 + wallHTotal : 3 + wallHTotal - 1;
    openings.push({ wall, tParam: (t + 1) / 2, widthCells, bottomY, topY });
  }

  // Build rectangular perimeter with openings.
  const wallCells: Array<{ x: number; z: number; wall: WallSide; tParam: number }> = [];
  for (let dx = -halfX; dx <= halfX; dx++) {
    wallCells.push({ x: dx, z: -halfZ, wall: "north", tParam: (dx + halfX) / (2 * halfX) });
    wallCells.push({ x: dx, z: halfZ, wall: "south", tParam: (dx + halfX) / (2 * halfX) });
  }
  for (let dz = -halfZ + 1; dz <= halfZ - 1; dz++) {
    wallCells.push({ x: -halfX, z: dz, wall: "west", tParam: (dz + halfZ) / (2 * halfZ) });
    wallCells.push({ x: halfX, z: dz, wall: "east", tParam: (dz + halfZ) / (2 * halfZ) });
  }
  for (const cell of wallCells) {
    if (!inFloor(cell.x, cell.z)) continue;
    for (let y = 3; y < 3 + wallHTotal; y++) {
      // Skip if this y range overlaps any opening on the same wall near the same tParam.
      let cut = false;
      for (const op of openings) {
        if (op.wall !== cell.wall) continue;
        const wallLen = cell.wall === "north" || cell.wall === "south" ? 2 * halfX : 2 * halfZ;
        const halfWidthParam = op.widthCells / wallLen;
        if (Math.abs(op.tParam - cell.tParam) > halfWidthParam) continue;
        if (y >= op.bottomY && y <= op.topY) { cut = true; break; }
      }
      if (cut) continue;
      if (rand() < 0.92) push("stone", cell.x, y, cell.z);
    }
  }

  // Per-feature voxel silhouettes — distinct shapes so a TV ≠ a plant ≠ a shelf.
  const sizeBump: Record<string, number> = { small: 0, medium: 1, large: 2 };
  for (const f of features) {
    if (f.kind === "door" || f.kind === "window") continue; // already handled by openings
    const wall: WallSide = (f.wall as WallSide) || "center";
    const sz = sizeBump[(f.size as string) || "medium"] ?? 1;
    // Resolve feature center: if against a wall, snap to ~2 cells inside that wall.
    const fx = Math.max(-0.9, Math.min(0.9, Number(f.x) || 0));
    const fz = Math.max(-0.9, Math.min(0.9, Number(f.z) || 0));
    let cx = Math.round(fx * (halfX - 3));
    let cz = Math.round(fz * (halfZ - 3));
    if (wall === "north") cz = -halfZ + 2;
    else if (wall === "south") cz = halfZ - 2;
    else if (wall === "west") cx = -halfX + 2;
    else if (wall === "east") cx = halfX - 2;
    placeFeature(push, isOccupied, rand, f.kind, cx, cz, wall, sz);
  }

  // Serialize.
  const serialized: Record<string, string> = {};
  let total = 0;
  for (const [name, arr] of Object.entries(buckets)) {
    const i32 = new Int32Array(arr);
    serialized[name] = Buffer.from(i32.buffer, i32.byteOffset, i32.byteLength).toString("base64");
    total += Math.floor(arr.length / 3);
  }
  return { layers: serialized, blockCount: total, span: Math.max(halfX, halfZ) * 2 };
}

type PushFn = (layer: string, x: number, y: number, z: number) => void;
type OccFn = (x: number, y: number, z: number) => boolean;

function placeFeature(push: PushFn, _isOcc: OccFn, rand: () => number, kind: string, cx: number, cz: number, wall: WallSide, sz: number) {
  const baseY = 3; // sit on top of the top-layer floor (y=2)
  // For wall-mounted things we tilt the silhouette so the long axis runs along the wall.
  const alongIsX = wall === "north" || wall === "south";
  switch (kind) {
    case "screen": {
      // Flat upright rectangle, 1 deep, ~ (2+sz)*2 wide × (2+sz) tall, mounted on wall.
      const wCells = 2 + sz;
      const hCells = 2 + sz;
      for (let i = -wCells; i <= wCells; i++) {
        for (let y = baseY + 1; y < baseY + 1 + hCells; y++) {
          if (alongIsX) push("metal", cx + i, y, cz);
          else push("metal", cx, y, cz + i);
        }
      }
      // dark frame
      for (let i = -wCells - 1; i <= wCells + 1; i++) {
        if (alongIsX) {
          push("stone", cx + i, baseY, cz);
          push("stone", cx + i, baseY + 1 + hCells, cz);
        } else {
          push("stone", cx, baseY, cz + i);
          push("stone", cx, baseY + 1 + hCells, cz + i);
        }
      }
      break;
    }
    case "table": {
      // Flat top with corner legs.
      const w = 1 + sz;
      const d = 1 + sz;
      // legs
      for (const lx of [-w, w]) for (const lz of [-d, d]) {
        push("stone", cx + lx, baseY, cz + lz);
      }
      // top slab
      for (let dx = -w; dx <= w; dx++) for (let dz = -d; dz <= d; dz++) {
        push("stone", cx + dx, baseY + 1, cz + dz);
      }
      break;
    }
    case "seat": {
      // L-shape: seat + low back.
      const w = 1 + Math.floor(sz / 2);
      for (let dx = -w; dx <= w; dx++) {
        push("dryGrass", cx + dx, baseY, cz);
      }
      // back wall
      for (let dx = -w; dx <= w; dx++) {
        if (alongIsX) push("dirt", cx + dx, baseY + 1, cz - (wall === "south" ? -1 : 1));
        else push("dirt", cx - (wall === "east" ? -1 : 1), baseY + 1, cz + dx);
      }
      break;
    }
    case "bed": {
      // Long flat platform 2 wide × (3 + sz) long along the wall.
      const w = 1; // half-width
      const len = 2 + sz;
      for (let along = -len; along <= len; along++) {
        for (let across = -w; across <= w; across++) {
          if (alongIsX) {
            push("dryGrass", cx + along, baseY, cz + across);
            push("dryGrass", cx + along, baseY + 1, cz + across);
          } else {
            push("dryGrass", cx + across, baseY, cz + along);
            push("dryGrass", cx + across, baseY + 1, cz + along);
          }
        }
      }
      // headboard
      for (let across = -w; across <= w; across++) {
        if (alongIsX) push("stone", cx + (wall === "east" ? 1 : -1) * (len + 1), baseY + 2, cz + across);
        else push("stone", cx + across, baseY + 2, cz + (wall === "north" ? -1 : 1) * (len + 1));
      }
      break;
    }
    case "shelf": {
      // Tall thin tower at the wall.
      const h = 4 + sz;
      for (let y = baseY; y < baseY + h; y++) push("stone", cx, y, cz);
      // a few sideways accent blocks (books)
      for (let y = baseY + 1; y < baseY + h; y += 2) {
        if (rand() < 0.7) {
          if (alongIsX) push("fruit", cx + (rand() < 0.5 ? -1 : 1), y, cz);
          else push("fruit", cx, y, cz + (rand() < 0.5 ? -1 : 1));
        }
      }
      break;
    }
    case "plant": {
      // Trunk + leaf canopy.
      const trunkH = 2 + Math.floor(sz / 2);
      for (let y = baseY; y < baseY + trunkH; y++) push("stone", cx, y, cz);
      const canopyY = baseY + trunkH;
      const r = 1 + Math.floor(sz / 2);
      for (let dx = -r; dx <= r; dx++) for (let dz = -r; dz <= r; dz++) {
        if (dx * dx + dz * dz > r * r + 1) continue;
        push("leaves", cx + dx, canopyY, cz + dz);
        if (rand() < 0.4) push("leaves", cx + dx, canopyY + 1, cz + dz);
      }
      break;
    }
    case "lamp": {
      // Pole + glowing fruit on top.
      const h = 3 + sz;
      for (let y = baseY; y < baseY + h; y++) push("stone", cx, y, cz);
      push("fruit", cx, baseY + h, cz);
      // halo
      for (const [dx, dz] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {
        if (rand() < 0.5) push("fruit", cx + dx, baseY + h, cz + dz);
      }
      break;
    }
    case "appliance": {
      // Tall rectangular box (fridge / oven / purifier).
      const w = 1, d = 1, h = 3 + sz;
      for (let dx = -w; dx <= w; dx++) for (let dz = -d; dz <= d; dz++) for (let y = baseY; y < baseY + h; y++) {
        push("metal", cx + dx, y, cz + dz);
      }
      break;
    }
    case "decor": {
      // Small colorful cluster.
      for (let i = 0; i < 4 + sz * 2; i++) {
        const ox = Math.round((rand() - 0.5) * (2 + sz));
        const oz = Math.round((rand() - 0.5) * (2 + sz));
        const oy = Math.floor(rand() * (1 + sz));
        push(rand() < 0.5 ? "fruit" : "leaves", cx + ox, baseY + oy, cz + oz);
      }
      break;
    }
    case "structure": {
      // Tall stone pillar.
      const h = 5 + sz;
      for (let y = baseY; y < baseY + h; y++) push("stone", cx, y, cz);
      break;
    }
    default: {
      // Generic feature: small dirt mound.
      for (let i = 0; i < 4 + sz; i++) {
        push("dirt", cx + Math.round((rand() - 0.5) * 2), baseY + Math.floor(rand() * 2), cz + Math.round((rand() - 0.5) * 2));
      }
    }
  }
}

async function runInference(captureId: string, db: Database) {
  const cap: any = db.query(`SELECT * FROM pending_captures WHERE id = ?`).get(captureId);
  if (!cap) throw new Error(`capture ${captureId} not found`);
  if (cap.world_id) {
    const world = db.query(`SELECT * FROM worlds WHERE id = ?`).get(cap.world_id);
    if (world) {
      return { reused: true, world, scene: cap.scene_json ? JSON.parse(cap.scene_json) : null, blockCount: (world as any).base_blocks };
    }
  }

  const apiKey = process.env.GEMINI_API_KEY || process.env.Gemini_API_key_v2;
  if (!apiKey) throw new Error("GEMINI_API_KEY not set");

  const tmpDir = `${TMP_BASE}/${captureId}`;
  try { rmSync(tmpDir, { recursive: true, force: true }); } catch {}
  const frames = extractKeyframes(cap.video_path, cap.duration_ms, tmpDir);
  const scene = await callGemini(apiKey, frames);
  try { rmSync(tmpDir, { recursive: true, force: true }); } catch {}

  const seedStr = `${captureId}|${cap.lat.toFixed(5)},${cap.lon.toFixed(5)}`;
  const { layers, blockCount, span } = generateLayers(scene, seedStr);

  const now = Date.now();
  const worldId = `w_${now.toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
  const worldName = (scene.name && String(scene.name).slice(0, 60)) || "Captured Space";

  db.run(
    `INSERT INTO worlds (id, name, lat, lon, owner, base_blocks, integrity, created_at, last_visited, last_scanned)
     VALUES (?, ?, ?, ?, ?, ?, 100, ?, ?, ?)`,
    [worldId, worldName, cap.lat, cap.lon, cap.owner, blockCount, now, now, now],
  );

  const meta = {
    voxel: 0.05,
    span,
    centerX: 0,
    centerZ: 0,
    blockCount,
    resolution: span,
    weatherSeason: scene.light === "night" ? "winter" : "summer",
    inferredFrom: { capture_id: captureId, scene, model: GEMINI_MODEL },
    savedAt: now,
  };
  const payload = JSON.stringify({ layers, meta });
  db.run(
    `INSERT INTO world_blocks (world_id, payload, block_count, resolution, updated_at)
     VALUES (?, ?, ?, ?, ?)`,
    [worldId, payload, blockCount, span, now],
  );

  db.run(
    `UPDATE pending_captures SET status = 'processed', world_id = ?, scene_json = ?, inferred_at = ? WHERE id = ?`,
    [worldId, JSON.stringify(scene), now, captureId],
  );

  const world = db.query(`SELECT * FROM worlds WHERE id = ?`).get(worldId);
  return { reused: false, world, scene, blockCount };
}

async function runGeometricInference(captureId: string, db: Database) {
  const cap: any = db.query(`SELECT * FROM pending_captures WHERE id = ?`).get(captureId);
  if (!cap) throw new Error(`capture ${captureId} not found`);
  if (cap.world_id) {
    const world = db.query(`SELECT * FROM worlds WHERE id = ?`).get(cap.world_id);
    if (world) {
      return { reused: true, world, scene: cap.scene_json ? JSON.parse(cap.scene_json) : null, blockCount: (world as any).base_blocks };
    }
  }

  const outPath = `${TMP_BASE}/${captureId}.geom.json`;
  try { rmSync(outPath, { force: true }); } catch {}
  mkdirSync(TMP_BASE, { recursive: true });

  const scriptArgs = [
    V2V_SCRIPT,
    cap.video_path,
    outPath,
    "--frames",
    "150",
    "--voxel",
    "0.08",
    "--max-step-m",
    "0.8",
    "--max-solidify-cells",
    "5000000",
  ];
  if (cap.imu_path) {
    scriptArgs.push("--imu", cap.imu_path);
  }
  const res = spawnSync(PYTHON_BIN, scriptArgs, { stdio: "pipe", timeout: 240_000 });
  if (res.status !== 0 || res.signal) {
    const tail = (res.stderr?.toString() || "").slice(-600);
    const reason = res.status !== null ? `exit=${res.status}` : `signal=${res.signal || "unknown"}`;
    throw new Error(`video_to_voxels failed (${reason}): ${tail}`);
  }
  let payload: any;
  try {
    payload = JSON.parse(readFileSync(outPath, "utf8"));
  } catch (e: any) {
    throw new Error(`failed to read geometric output: ${e?.message || e}`);
  }
  try { rmSync(outPath, { force: true }); } catch {}

  const layers = payload?.layers || {};
  const blockCount = Number(payload?.blockCount || 0);
  const span = Number(payload?.span || 0);
  if (!blockCount) throw new Error("geometric inference produced 0 blocks");

  const now = Date.now();
  const worldId = `w_geo_${now.toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
  const worldName = `Geometric Scan ${new Date(now).toISOString().slice(0, 10)}`;

  db.run(
    `INSERT INTO worlds (id, name, lat, lon, owner, base_blocks, integrity, created_at, last_visited, last_scanned)
     VALUES (?, ?, ?, ?, ?, ?, 100, ?, ?, ?)`,
    [worldId, worldName, cap.lat, cap.lon, cap.owner, blockCount, now, now, now],
  );

  const meta = {
    voxel: payload?.meta?.voxel ?? 0.08,
    span,
    centerX: 0,
    centerZ: 0,
    blockCount,
    resolution: span,
    weatherSeason: "summer",
    inferredFrom: {
      capture_id: captureId,
      source: "video_to_voxels.py",
      model: "depth-anything-v2-metric-indoor-small + open3d-tsdf",
      script_meta: payload?.meta,
      imu_used: !!payload?.meta?.imu_used,
      imu_samples: Number(payload?.meta?.imu_samples || 0),
    },
    savedAt: now,
  };
  db.run(
    `INSERT INTO world_blocks (world_id, payload, block_count, resolution, updated_at)
     VALUES (?, ?, ?, ?, ?)`,
    [worldId, JSON.stringify({ layers, meta }), blockCount, span, now],
  );

  db.run(
    `UPDATE pending_captures SET status = 'processed', world_id = ?, inferred_at = ? WHERE id = ?`,
    [worldId, now, captureId],
  );

  const world = db.query(`SELECT * FROM worlds WHERE id = ?`).get(worldId);
  return {
    reused: false,
    world,
    scene: null,
    blockCount,
    geometric: true,
    imu_used: !!payload?.meta?.imu_used,
    imu_samples: Number(payload?.meta?.imu_samples || 0),
  };
}

// Runs merge_capture_into_world.py and returns its final JSON decision line.
// The script itself enforces the gate + coverage guard and never overwrites the
// target world unless both scans co-registered ("geometry decides").
async function runMergeAttempt(captureId: string, intoWorldId: string): Promise<any> {
  const args = [MERGE_SCRIPT, captureId, "--into-world-id", intoWorldId, "--target-divs", "300"];
  const child = spawn(OLD_PATH_PYTHON, args, {
    stdio: ["ignore", "pipe", "pipe"],
    env: { ...process.env, GLB_PYTHON: OLD_PATH_PYTHON },
  });
  let out = "";
  let err = "";
  child.stdout?.on("data", (d: any) => { out = (out + d.toString()).slice(-16000); });
  child.stderr?.on("data", (d: any) => { err = (err + d.toString()).slice(-1600); });
  let timedOut = false;
  const killer = setTimeout(() => { timedOut = true; try { child.kill("SIGKILL"); } catch {} }, INFER_TIMEOUT_MS);
  const exitCode = await new Promise<number | null>((resolve, reject) => {
    child.on("error", reject);
    child.on("exit", (code: number | null) => resolve(code));
  });
  clearTimeout(killer);
  if (timedOut) {
    return { ok: false, decision: "error", reason: `merge attempt timed out after ${INFER_TIMEOUT_MS / 60000} min`, exit: exitCode };
  }
  for (const line of out.trim().split("\n").reverse()) {
    const t = line.trim();
    if (t.startsWith("{")) {
      try { return JSON.parse(t); } catch {}
    }
  }
  return { ok: false, decision: "error", exit: exitCode, stderr: err.slice(-600) };
}

async function runOpenMvsInference(captureId: string, db: Database) {
  const cap: any = db.query(`SELECT * FROM pending_captures WHERE id = ?`).get(captureId);
  if (!cap) throw new Error(`capture ${captureId} not found`);
  if (cap.world_id) {
    const world = db.query(`SELECT * FROM worlds WHERE id = ?`).get(cap.world_id) as any;
    const block = db.query(`SELECT block_count FROM world_blocks WHERE world_id = ?`).get(cap.world_id) as any;
    if (world && block && cap.status === "processed") {
      return { reused: true, world, scene: null, blockCount: Number(block.block_count || world.base_blocks || 0), openmvs: true };
    }
    if (!world) {
      // Stale pointer at a since-deleted world (e.g. old stuck row being
      // retried) — clear it so this run mints a fresh world instead of
      // writing orphaned blocks under a world id that no longer exists.
      db.run(`UPDATE pending_captures SET world_id = NULL WHERE id = ?`, [captureId]);
      cap.world_id = null;
    }
  }

  // Merge-at-most: GPS nominated a candidate at capture time; geometry decides
  // here. On co-registration the capture merges INTO the candidate world (its
  // prior payload is backed up first). Any other outcome falls through and
  // mints a SEPARATE world — no path blind-overwrites an existing world.
  if (!cap.world_id && cap.merge_candidate_world_id) {
    const candidate = db.query(`SELECT id FROM worlds WHERE id = ?`).get(cap.merge_candidate_world_id) as any;
    if (candidate) {
      const merge = await runMergeAttempt(captureId, cap.merge_candidate_world_id);
      db.run(
        `UPDATE pending_captures SET merge_decision = ? WHERE id = ?`,
        [JSON.stringify(merge ?? { decision: "error" }).slice(0, 2000), captureId],
      );
      if (merge?.decision === "merged") {
        const now = Date.now();
        db.run(
          `UPDATE pending_captures SET status = 'processed', world_id = ?, inferred_at = ? WHERE id = ?`,
          [cap.merge_candidate_world_id, now, captureId],
        );
        const world = db.query(`SELECT * FROM worlds WHERE id = ?`).get(cap.merge_candidate_world_id);
        return {
          reused: false, world, scene: null,
          blockCount: Number(merge.block_count || 0),
          openmvs: true, merged: true,
          merge: { decision: merge.decision, old_blocks: merge.old_blocks, backup: merge.backup, gate: merge.gate?.shared_model ?? null },
        };
      }
      console.log(`[infer] merge declined for ${captureId} -> ${cap.merge_candidate_world_id}: ${merge?.decision} (${merge?.reason || "no reason"}); minting separate world`);
    }
  }

  const now0 = Date.now();
  const worldId = cap.world_id || `w_glb_${now0.toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
  const worldName = `OpenMVS Scan ${new Date(now0).toISOString().slice(0, 10)}`;
  if (!cap.world_id) {
    db.run(
      `INSERT INTO worlds (id, name, lat, lon, owner, base_blocks, integrity, created_at, last_visited, last_scanned)
       VALUES (?, ?, ?, ?, ?, 0, 100, ?, ?, ?)`,
      [worldId, worldName, cap.lat, cap.lon, cap.owner, now0, now0, now0],
    );
    db.run(`UPDATE pending_captures SET world_id = ? WHERE id = ?`, [worldId, captureId]);
  }

  const scanId = `scan_from_${captureId}`;
  const args = [
    OLD_PATH_SCRIPT,
    captureId,
    "--world-id", worldId,
    "--scan-id", scanId,
    "--reset",
    "--target-divs", "180",
  ];
  const child = spawn(OLD_PATH_PYTHON, args, {
    stdio: ["ignore", "pipe", "pipe"],
    env: { ...process.env, GLB_PYTHON: OLD_PATH_PYTHON },
  });
  let stdoutTail = "";
  let stderrTail = "";
  child.stdout?.on("data", (d: any) => { stdoutTail = (stdoutTail + d.toString()).slice(-1600); });
  child.stderr?.on("data", (d: any) => { stderrTail = (stderrTail + d.toString()).slice(-1600); });
  let timedOut = false;
  const killer = setTimeout(() => { timedOut = true; try { child.kill("SIGKILL"); } catch {} }, INFER_TIMEOUT_MS);
  const exitCode = await new Promise<number | null>((resolve, reject) => {
    child.on("error", reject);
    child.on("exit", (code: number | null) => resolve(code));
  });
  clearTimeout(killer);
  if (timedOut) {
    throw new Error(`OpenMVS/GLB pipeline timed out after ${INFER_TIMEOUT_MS / 60000} min — retry, or rescan with a shorter capture`);
  }
  if (exitCode !== 0) {
    throw new Error(`OpenMVS/GLB pipeline failed (exit=${exitCode}): ${(stderrTail || stdoutTail).slice(-700)}`);
  }

  const block = db.query(`SELECT block_count, resolution FROM world_blocks WHERE world_id = ?`).get(worldId) as any;
  if (!block || !Number(block.block_count || 0)) throw new Error("OpenMVS/GLB pipeline produced no saved blocks");
  const now = Date.now();
  db.run(`UPDATE pending_captures SET status = 'processed', inferred_at = ? WHERE id = ?`, [now, captureId]);
  db.run(`UPDATE worlds SET base_blocks = ?, last_scanned = ?, last_visited = ? WHERE id = ?`, [Number(block.block_count || 0), now, now, worldId]);
  const world = db.query(`SELECT * FROM worlds WHERE id = ?`).get(worldId);
  return { reused: false, world, scene: null, blockCount: Number(block.block_count || 0), resolution: Number(block.resolution || 0), openmvs: true, scanId };
}

// ---------------------------------------------------------------------------
// Progressive (windowed) geometric inference.
//
// Spawns video_to_voxels.py --progressive (non-blocking), which streams zones
// into a zone dir as it processes the video in temporal order. This worker
// watches the dir's manifest and inserts each new zone into world_zones the
// moment it lands, so the GET poll can reveal the world growing zone-by-zone
// (first island ~25s vs ~150s for a single shot). All zones share one origin
// (continuous odometry), so they stack without any inter-chunk alignment.
// ---------------------------------------------------------------------------
const V2V_PROG = { firstWindow: "3", window: "3", overlap: "1", fps: "4", voxel: "0.08" };
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

// Concatenate per-layer coordinate arrays across zones into one payload. Every
// zone is serialized against the same shared origin, so a plain concat of the
// int32 triplets yields the union world.
function mergeZoneLayers(layerMaps: Array<Record<string, string>>): { layers: Record<string, string>; blockCount: number } {
  const acc: Record<string, number[]> = {};
  for (const layers of layerMaps) {
    if (!layers) continue;
    for (const [name, b64] of Object.entries(layers)) {
      const buf = Buffer.from(b64, "base64");
      const n = Math.floor(buf.byteLength / 4);
      const i32 = new Int32Array(buf.buffer, buf.byteOffset, n);
      const dst = acc[name] || (acc[name] = []);
      for (let k = 0; k < n; k++) dst.push(i32[k]);
    }
  }
  const serialized: Record<string, string> = {};
  let total = 0;
  for (const [name, arr] of Object.entries(acc)) {
    const i32 = new Int32Array(arr);
    serialized[name] = Buffer.from(i32.buffer, i32.byteOffset, i32.byteLength).toString("base64");
    total += Math.floor(arr.length / 3);
  }
  return { layers: serialized, blockCount: total };
}

async function runProgressiveInference(captureId: string, db: Database) {
  const cap: any = db.query(`SELECT * FROM pending_captures WHERE id = ?`).get(captureId);
  if (!cap) throw new Error(`capture ${captureId} not found`);
  if (cap.world_id) {
    const world = db.query(`SELECT * FROM worlds WHERE id = ?`).get(cap.world_id);
    if (world) {
      return { reused: true, world, scene: null, blockCount: (world as any).base_blocks, progressive: true };
    }
  }

  const zoneDir = `${TMP_BASE}/${captureId}.zones`;
  try { rmSync(zoneDir, { recursive: true, force: true }); } catch {}
  mkdirSync(zoneDir, { recursive: true });

  const now0 = Date.now();
  const worldId = `w_prog_${now0.toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
  const worldName = `Progressive Scan ${new Date(now0).toISOString().slice(0, 10)}`;

  // Create the world + attach to the capture up front so the GET poll can
  // surface zones as they stream in (status stays 'inferring' until done).
  db.run(
    `INSERT INTO worlds (id, name, lat, lon, owner, base_blocks, integrity, created_at, last_visited, last_scanned)
     VALUES (?, ?, ?, ?, ?, 0, 100, ?, ?, ?)`,
    [worldId, worldName, cap.lat, cap.lon, cap.owner, now0, now0, now0],
  );
  db.run(`UPDATE pending_captures SET world_id = ? WHERE id = ?`, [worldId, captureId]);

  const args = [
    V2V_SCRIPT, cap.video_path, `${zoneDir}/world.json`,
    "--progressive", "--zone-dir", zoneDir,
    "--first-window", V2V_PROG.firstWindow,
    "--window", V2V_PROG.window,
    "--overlap", V2V_PROG.overlap,
    "--fps", V2V_PROG.fps,
    "--voxel", V2V_PROG.voxel,
    "--max-step-m", "0.8",
    "--max-solidify-cells", "5000000",
  ];
  if (cap.imu_path) args.push("--imu", cap.imu_path);

  const child = spawn(PYTHON_BIN, args, { stdio: ["ignore", "ignore", "pipe"] });
  let stderrTail = "";
  child.stderr?.on("data", (d: any) => { stderrTail = (stderrTail + d.toString()).slice(-1200); });
  let exited = false; let exitCode: number | null = null; let spawnErr: any = null;
  child.on("error", (e: any) => { spawnErr = e; exited = true; });
  child.on("exit", (code: number | null) => { exited = true; exitCode = code; });

  const inserted = new Set<number>();
  const zoneLayerById = new Map<number, Record<string, string>>();
  let totalBlocks = 0;
  const deadline = now0 + 360_000;

  const drainManifest = (): { status: string; zoneCount: number } => {
    let manifest: any = null;
    try { manifest = JSON.parse(readFileSync(`${zoneDir}/manifest.json`, "utf8")); } catch {}
    if (manifest && Array.isArray(manifest.zones)) {
      for (const z of manifest.zones) {
        if (inserted.has(z.index)) continue;
        let zdata: any = null;
        try { zdata = JSON.parse(readFileSync(`${zoneDir}/${z.file}`, "utf8")); } catch { continue; }
        const payload = JSON.stringify({ layers: zdata.layers, origin: zdata.origin });
        db.run(
          `INSERT OR REPLACE INTO world_zones (world_id, zone_index, kind, payload, block_count, t_start, t_end, created_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
          [worldId, z.index, z.kind || "scan", payload, Number(zdata.blockCount || 0), zdata.t_start ?? null, zdata.t_end ?? null, Date.now()],
        );
        inserted.add(z.index);
        zoneLayerById.set(z.index, zdata.layers || {});
        totalBlocks += Number(zdata.blockCount || 0);
        db.run(`UPDATE worlds SET base_blocks = ? WHERE id = ?`, [totalBlocks, worldId]);
      }
      return { status: manifest.status || "running", zoneCount: manifest.zones.length };
    }
    return { status: "running", zoneCount: 0 };
  };

  while (true) {
    const { status, zoneCount } = drainManifest();
    if (status === "done" && inserted.size >= zoneCount) break;
    if (status === "error") throw new Error(`progressive script error: ${stderrTail.slice(-400)}`);
    if (spawnErr) throw new Error(`failed to spawn progressive script: ${spawnErr?.message || spawnErr}`);
    if (exited) {
      drainManifest();
      if (exitCode !== 0 && inserted.size === 0) {
        throw new Error(`progressive script exited ${exitCode}: ${stderrTail.slice(-400)}`);
      }
      break;
    }
    if (Date.now() > deadline) { try { child.kill(); } catch {} break; }
    await sleep(1200);
  }

  if (inserted.size === 0) throw new Error(`progressive inference produced 0 zones: ${stderrTail.slice(-400)}`);

  // Consolidate into a single world_blocks payload so the world is openable by
  // the standard (non-progressive) loader once complete. Prefer the final
  // coherent global fuse (world.json) the script writes over the whole TSDF —
  // the per-window zones carry odometry drift and concatenating them scatters
  // the geometry. Fall back to a zone concat only if the fuse is missing/empty.
  let mergedLayers: Record<string, string>;
  let mergedCount: number;
  let span: number;
  let consolidation: string;
  let fuse: any = null;
  try { fuse = JSON.parse(readFileSync(`${zoneDir}/world.json`, "utf8")); } catch {}
  if (fuse && fuse.layers && Number(fuse.blockCount) > 0) {
    mergedLayers = fuse.layers;
    mergedCount = Number(fuse.blockCount);
    span = Number(fuse.span || 0);
    consolidation = "global-fuse";
  } else {
    const ordered = [...zoneLayerById.entries()].sort((a, b) => a[0] - b[0]).map((e) => e[1]);
    const merged = mergeZoneLayers(ordered);
    mergedLayers = merged.layers;
    mergedCount = merged.blockCount;
    let minX = Infinity, maxX = -Infinity, minZ = Infinity, maxZ = -Infinity;
    for (const b64 of Object.values(mergedLayers)) {
      const buf = Buffer.from(b64, "base64");
      const n = Math.floor(buf.byteLength / 4);
      const i32 = new Int32Array(buf.buffer, buf.byteOffset, n);
      for (let k = 0; k + 2 < n; k += 3) {
        const x = i32[k], z = i32[k + 2];
        if (x < minX) minX = x; if (x > maxX) maxX = x;
        if (z < minZ) minZ = z; if (z > maxZ) maxZ = z;
      }
    }
    span = isFinite(minX) ? Math.max(maxX - minX, maxZ - minZ) : 0;
    consolidation = "zone-concat";
  }

  const now = Date.now();
  const meta = {
    voxel: 0.08,
    span,
    centerX: 0,
    centerZ: 0,
    blockCount: mergedCount,
    resolution: span,
    weatherSeason: "summer",
    progressive: true,
    consolidation,
    inferredFrom: {
      capture_id: captureId,
      source: "video_to_voxels.py:progressive",
      model: "depth-anything-v2-metric-indoor-small + open3d-tsdf",
      zones: inserted.size,
      consolidation,
      imu_used: !!cap.imu_path,
    },
    savedAt: now,
  };
  db.run(
    `INSERT OR REPLACE INTO world_blocks (world_id, payload, block_count, resolution, updated_at)
     VALUES (?, ?, ?, ?, ?)`,
    [worldId, JSON.stringify({ layers: mergedLayers, meta }), mergedCount, span, now],
  );
  db.run(`UPDATE worlds SET base_blocks = ? WHERE id = ?`, [mergedCount, worldId]);
  db.run(`UPDATE pending_captures SET status = 'processed', inferred_at = ? WHERE id = ?`, [now, captureId]);
  try { rmSync(zoneDir, { recursive: true, force: true }); } catch {}

  const world = db.query(`SELECT * FROM worlds WHERE id = ?`).get(worldId);
  return { reused: false, world, scene: null, blockCount: mergedCount, progressive: true, zones: inserted.size };
}

export default async function handler(c: Context) {
  if (c.req.method === "GET") {
    const id = c.req.query("capture_id");
    if (!id) return c.json({ ok: false, error: "capture_id query param required" }, 400);
    const db = getDb();
    try {
      const cap: any = db.query(`SELECT id, status, world_id, scene_json, inferred_at, error_msg, inference_started_at FROM pending_captures WHERE id = ?`).get(id);
      if (!cap) return c.json({ ok: false, error: "capture not found" }, 404);

      // Single-zone payload fetch: ?capture_id=...&zone=N
      const zoneParam = c.req.query("zone");
      if (zoneParam != null) {
        if (!cap.world_id) return c.json({ ok: false, error: "no world for capture" }, 404);
        const zrow: any = db.query(
          `SELECT zone_index, kind, payload, block_count, t_start, t_end FROM world_zones WHERE world_id = ? AND zone_index = ?`,
        ).get(cap.world_id, Number(zoneParam));
        if (!zrow) return c.json({ ok: false, error: "zone not found" }, 404);
        return c.json({ ok: true, zone: { ...zrow, payload: JSON.parse(zrow.payload) } });
      }

      let world: any = null;
      let blockCount: number | null = null;
      let zones: any[] = [];
      if (cap.world_id) {
        world = db.query(`SELECT * FROM worlds WHERE id = ?`).get(cap.world_id);
        if (world) blockCount = (world as any).base_blocks;
        zones = db.query(
          `SELECT zone_index, kind, block_count, t_start, t_end, created_at FROM world_zones WHERE world_id = ? ORDER BY zone_index`,
        ).all(cap.world_id);
      }
      return c.json({
        ok: true,
        status: cap.status,
        world_id: cap.world_id,
        world,
        blockCount,
        zones,
        scene: cap.scene_json ? JSON.parse(cap.scene_json) : null,
        inferred_at: cap.inferred_at,
        inference_started_at: cap.inference_started_at,
        worker_alive: cap.status === "inferring" ? liveWorkers.has(cap.id) : undefined,
        error: cap.error_msg || null,
      });
    } finally {
      db.close();
    }
  }

  if (c.req.method !== "POST") return c.json({ ok: false, error: "method not allowed" }, 405);

  let body: any;
  try { body = await c.req.json(); } catch { return c.json({ ok: false, error: "JSON body required" }, 400); }
  const captureId = body?.capture_id;
  if (typeof captureId !== "string" || !captureId) {
    return c.json({ ok: false, error: "capture_id required" }, 400);
  }
  const useGeometry = body?.geometry === true || body?.mode === "geometric"
    || c.req.query("geometry") === "1";
  const useProgressive = body?.progressive === true || body?.mode === "progressive"
    || c.req.query("progressive") === "1";
  const useProcedural = body?.procedural === true || body?.mode === "procedural"
    || c.req.query("procedural") === "1";
  const startAsync = body?.start_async === true || c.req.query("async") === "1";

  if (startAsync) {
    const db = getDb();
    try {
      const cap: any = db.query(`SELECT id, status, world_id FROM pending_captures WHERE id = ?`).get(captureId);
      if (!cap) return c.json({ ok: false, error: "capture not found" }, 404);
      // If already processed, return immediately so the client can poll once and finish.
      if (cap.world_id && cap.status === "processed") {
        return c.json({ ok: true, queued: false, status: "processed", capture_id: captureId, world_id: cap.world_id });
      }
      // Only acknowledge "already inferring" when a worker is genuinely alive
      // in this process. If the row says 'inferring' but no worker exists
      // (server restarted mid-flight), fall through and restart the work —
      // this is the retry path that used to be silently swallowed.
      if (cap.status === "inferring") {
        if (liveWorkers.has(captureId)) {
          return c.json({ ok: true, queued: true, status: "inferring", capture_id: captureId });
        }
        console.log(`[infer] ${captureId} marked 'inferring' with no live worker — restarting`);
      }
      const now = Date.now();
      db.run(`UPDATE pending_captures SET status = 'inferring', inference_started_at = ?, error_msg = NULL WHERE id = ?`, [now, captureId]);
    } finally {
      db.close();
    }
    liveWorkers.add(captureId);
    // Fire-and-forget worker. Use its own db handle.
    setTimeout(() => {
      (async () => {
        const workerDb = getDb();
        const workerStartedAt = Date.now();
        try {
          let result: any;
          if (useProgressive) {
            result = await runProgressiveInference(captureId, workerDb);
          } else if (useGeometry) {
            result = await runGeometricInference(captureId, workerDb);
          } else if (useProcedural) {
            result = await runInference(captureId, workerDb);
          } else {
            result = await runOpenMvsInference(captureId, workerDb);
          }
          // reused=true means the row was already processed (idempotent
          // re-entry) — nothing new happened, so no ping.
          if (result && !result.reused) {
            notifyScanResult({
              ok: true,
              captureId,
              worldId: result.world?.id,
              worldName: result.world?.name,
              blockCount: Number(result.blockCount || 0),
              merged: !!result.merged,
              elapsedMs: Date.now() - workerStartedAt,
            });
          }
        } catch (e: any) {
          console.error("async infer failed:", e);
          try {
            workerDb.run(
              `UPDATE pending_captures SET status = 'failed', error_msg = ? WHERE id = ?`,
              [String(e?.message || e).slice(0, 600), captureId],
            );
          } catch {}
          notifyScanResult({
            ok: false,
            captureId,
            error: String(e?.message || e),
            elapsedMs: Date.now() - workerStartedAt,
          });
        } finally {
          liveWorkers.delete(captureId);
          try { workerDb.close(); } catch {}
        }
      })();
    }, 0);
    return c.json({ ok: true, queued: true, status: "inferring", capture_id: captureId });
  }

  const db = getDb();
  try {
    const result = useProgressive
      ? await runProgressiveInference(captureId, db)
      : useGeometry
        ? await runGeometricInference(captureId, db)
        : useProcedural
          ? await runInference(captureId, db)
          : await runOpenMvsInference(captureId, db);
    return c.json({ ok: true, ...result });
  } catch (e: any) {
    console.error("infer failed:", e);
    try {
      db.run(`UPDATE pending_captures SET status = 'failed', error_msg = ? WHERE id = ?`, [String(e?.message || e).slice(0, 600), captureId]);
    } catch {}
    return c.json({ ok: false, error: e?.message || String(e) }, 500);
  } finally {
    db.close();
  }
}
