// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { Database } from "bun:sqlite";
import { mkdirSync, writeFileSync, existsSync, readdirSync, statSync, readFileSync } from "node:fs";

const DATA_DIR = "/home/workspace/project-tinyworld/data";
const DB_PATH = `${DATA_DIR}/tinyworld.db`;
const CAPTURES_DIR = `${DATA_DIR}/captures`;

// Re-scan gate rules (kept in sync with /api/tinyworld-scan).
const SCAN_REGION_RADIUS_M = 150;
// Tiered placement, shared GPS-distance basis with the client multi-world loader:
//   <= MERGE_NOMINATE_RADIUS_M (owned) -> NOMINATE as merge candidate (geometry decides at infer)
//   MERGE_NOMINATE_RADIUS_M .. ~100m   -> new world, rendered adjacent (full) by client
//   > ~100m                            -> new world, rendered as a silhouette impostor
// Replace is banned. GPS proximity only nominates a merge; joint co-registration
// at infer time decides. Without shared geometry the scan becomes a separate
// world — an existing world is never blind-overwritten (Greene St, 2026-07-01).
const MERGE_NOMINATE_RADIUS_M = 50;
const WEATHERED_AFTER_MS = 180 * 24 * 3600 * 1000;
const MAX_VIDEO_BYTES = 80 * 1024 * 1024; // 80 MB hard cap per upload

function getDb() {
  mkdirSync(DATA_DIR, { recursive: true });
  mkdirSync(CAPTURES_DIR, { recursive: true });
  const db = new Database(DB_PATH);
  db.run(`CREATE TABLE IF NOT EXISTS pending_captures (
    id TEXT PRIMARY KEY,
    lat REAL NOT NULL,
    lon REAL NOT NULL,
    owner TEXT NOT NULL,
    name TEXT,
    duration_ms INTEGER NOT NULL,
    bytes INTEGER NOT NULL,
    mime TEXT,
    video_path TEXT NOT NULL,
    captured_at INTEGER NOT NULL,
    status TEXT DEFAULT 'pending',
    gate_status TEXT,
    gate_reason TEXT
  )`);
  // Additive: IMU column added on existing installs without breaking the row layout.
  try {
    db.run(`ALTER TABLE pending_captures ADD COLUMN imu_path TEXT`);
  } catch {
    // already present
  }
  try {
    db.run(`ALTER TABLE pending_captures ADD COLUMN imu_samples INTEGER DEFAULT 0`);
  } catch {
    // already present
  }
  // Additive: world_id is stamped by the INFER pipeline once the capture lands
  // in a world (merged or newly minted). Never pre-stamped at capture time.
  try {
    db.run(`ALTER TABLE pending_captures ADD COLUMN world_id TEXT`);
  } catch {
    // already present
  }
  // Additive: GPS-nominated merge candidate. Nomination only — geometry decides.
  try {
    db.run(`ALTER TABLE pending_captures ADD COLUMN merge_candidate_world_id TEXT`);
  } catch {
    // already present
  }
  db.run(`CREATE TABLE IF NOT EXISTS cataclysm_zones (
    id TEXT PRIMARY KEY,
    lat REAL NOT NULL,
    lon REAL NOT NULL,
    radius_m REAL NOT NULL,
    started_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    reason TEXT
  )`);
  return db;
}

function haversineMeters(lat1: number, lon1: number, lat2: number, lon2: number) {
  const R = 6371000;
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}

type GateStatus = "clear" | "blocked" | "exception_owner" | "exception_weathered" | "exception_cataclysm";
type GateDecision = {
  status: GateStatus;
  canScan: boolean;
  reason: string;
  appliedException: "owner" | "weathered" | "cataclysm" | null;
};

function evaluateGate(db: Database, lat: number, lon: number, owner: string): GateDecision {
  const now = Date.now();
  const worlds = db.query(`SELECT id, name, lat, lon, owner, last_scanned FROM worlds`).all() as any[];
  const conflicts = worlds.filter((w) => haversineMeters(lat, lon, w.lat, w.lon) <= SCAN_REGION_RADIUS_M);
  if (conflicts.length === 0) {
    return { status: "clear", canScan: true, reason: "No existing scan within the region radius.", appliedException: null };
  }
  if (owner && conflicts.every((c: any) => c.owner === owner)) {
    return { status: "exception_owner", canScan: true, reason: `Re-scanning your own territory: ${conflicts.map((c: any) => c.name).join(", ")}.`, appliedException: "owner" };
  }
  if (conflicts.every((c: any) => now - c.last_scanned > WEATHERED_AFTER_MS)) {
    return { status: "exception_weathered", canScan: true, reason: `All conflicting scans are weathered.`, appliedException: "weathered" };
  }
  const cataclysms = db.query(`SELECT lat, lon, radius_m, reason FROM cataclysm_zones WHERE expires_at > ?`).all(now) as any[];
  for (const cz of cataclysms) {
    if (haversineMeters(lat, lon, cz.lat, cz.lon) <= cz.radius_m) {
      return { status: "exception_cataclysm", canScan: true, reason: `Active cataclysm zone: ${cz.reason || "unspecified"}.`, appliedException: "cataclysm" };
    }
  }
  const youngest = conflicts.reduce((a: any, b: any) => (a.last_scanned > b.last_scanned ? a : b));
  return {
    status: "blocked",
    canScan: false,
    reason: `Conflicts with "${youngest.name}" by '${youngest.owner}', ${Math.round(haversineMeters(lat, lon, youngest.lat, youngest.lon))}m away. No exception applies.`,
    appliedException: null,
  };
}

export default async function handler(c: Context) {
  if (c.req.method === "GET") {
    // Listing endpoint for debugging — returns recent captures (metadata only).
    const db = getDb();
    try {
      const rows = db.query(`SELECT * FROM pending_captures ORDER BY captured_at DESC LIMIT 50`).all();
      return c.json({ ok: true, captures: rows });
    } finally {
      db.close();
    }
  }

  if (c.req.method !== "POST") {
    return c.json({ ok: false, error: "method not allowed" }, 405);
  }

  let form: FormData;
  try {
    form = await c.req.formData();
  } catch {
    return c.json({ ok: false, error: "expected multipart/form-data with a 'video' field" }, 400);
  }

  const video = form.get("video");
  const imuField = form.get("imu");
  const lat = Number(form.get("lat"));
  const lon = Number(form.get("lon"));
  const duration_ms = Math.max(0, Math.floor(Number(form.get("duration_ms") || 0)));
  const owner = String(form.get("owner") || c.req.header("x-owner-id") || "kj");
  const name = (form.get("name") as string | null)?.toString().trim() || null;

  if (!(video instanceof File) && !(video instanceof Blob)) {
    return c.json({ ok: false, error: "missing 'video' file field" }, 400);
  }
  if (Number.isNaN(lat) || Number.isNaN(lon)) {
    return c.json({ ok: false, error: "lat and lon (numbers) are required" }, 400);
  }
  const bytes = (video as any).size as number;
  if (bytes > MAX_VIDEO_BYTES) {
    return c.json({ ok: false, error: `video too large (${bytes} > ${MAX_VIDEO_BYTES} bytes)` }, 413);
  }
  if (duration_ms <= 0) {
    return c.json({ ok: false, error: "duration_ms must be > 0" }, 400);
  }

  const db = getDb();
  try {
    const gate = evaluateGate(db, lat, lon, owner);
    if (!gate.canScan) {
      return c.json({ ok: false, gate, error: "scan blocked by gate" }, 409);
    }

    // Merge-nominate tier: if this capture sits near a world the same owner
    // already holds, stamp it as a merge CANDIDATE only. The infer pipeline
    // attempts joint co-registration ("geometry decides"): with real shared
    // geometry it merges into that world non-destructively (prior payload
    // backed up first); without it, the capture mints a separate world.
    let mergeCandidateId: string | null = null;
    {
      const owned = db.query(`SELECT id, lat, lon FROM worlds WHERE owner = ?`).all(owner) as any[];
      let best: { id: string; d: number } | null = null;
      for (const w of owned) {
        const d = haversineMeters(lat, lon, w.lat, w.lon);
        if (d <= MERGE_NOMINATE_RADIUS_M && (!best || d < best.d)) best = { id: w.id, d };
      }
      if (best) mergeCandidateId = best.id;
    }

    const now = Date.now();
    const id = `cap_${now.toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
    const mime = (video as any).type || "video/webm";
    const ext = mime.includes("mp4") ? "mp4" : "webm";
    const videoPath = `${CAPTURES_DIR}/${id}.${ext}`;
    const buf = Buffer.from(await (video as Blob).arrayBuffer());
    writeFileSync(videoPath, buf);

    // Optional IMU sidecar: a JSON blob from DeviceMotion sampling on the
    // browser side. Persist only if present + well-formed; never let a bad
    // IMU payload block the capture itself.
    let imuPath: string | null = null;
    let imuSamples = 0;
    if (imuField instanceof File || imuField instanceof Blob) {
      try {
        const imuBuf = Buffer.from(await (imuField as Blob).arrayBuffer());
        if (imuBuf.byteLength > 0 && imuBuf.byteLength < 4 * 1024 * 1024) {
          const parsed = JSON.parse(imuBuf.toString("utf-8"));
          if (parsed && Array.isArray(parsed.samples)) {
            imuSamples = parsed.samples.length;
            imuPath = `${CAPTURES_DIR}/${id}.imu.json`;
            writeFileSync(imuPath, imuBuf);
          }
        }
      } catch {
        // ignore malformed IMU payload — capture still succeeds without it
      }
    }

    writeFileSync(`${CAPTURES_DIR}/${id}.json`, JSON.stringify({
      id, lat, lon, owner, name, duration_ms, bytes, mime,
      captured_at: now, gate, imu_path: imuPath, imu_samples: imuSamples,
      merge_candidate_world_id: mergeCandidateId,
    }, null, 2));

    db.run(
      `INSERT INTO pending_captures (id, lat, lon, owner, name, duration_ms, bytes, mime, video_path, captured_at, status, gate_status, gate_reason, imu_path, imu_samples, merge_candidate_world_id)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?, ?, ?, ?)`,
      [id, lat, lon, owner, name, duration_ms, bytes, mime, videoPath, now, gate.status, gate.reason, imuPath, imuSamples, mergeCandidateId],
    );

    return c.json({
      ok: true,
      capture: { id, lat, lon, owner, name, duration_ms, bytes, mime, captured_at: now, imu_samples: imuSamples, merge_candidate_world_id: mergeCandidateId },
      gate,
      message: mergeCandidateId
        ? `Capture stored. GPS nominated a merge into ${mergeCandidateId} — shared geometry decides at infer.`
        : "Capture stored. Will mint a new world at infer.",
    });
  } finally {
    db.close();
  }
}
