#!/usr/bin/env bash
# Reapply the verified-good tinyworld-staging route to zo.space.
# Restores BOTH the disk file AND the .routes.json DB entry so the route
# survives space syncs (a disk-only edit gets wiped to a stub on sync).
set -euo pipefail

GOOD="/home/workspace/project-tinyworld/.route-backups/tinyworld-staging-20260627T222814Z-progressive-fix.tsx"
DISK="/__substrate/space/routes/pages/tinyworld-staging.tsx"
ROUTES_JSON="/__substrate/space/.routes.json"

[ -f "$GOOD" ] || { echo "ABORT: good backup not found at $GOOD"; exit 1; }

echo "[1/5] Back up current disk + .routes.json"
cp "$DISK" "${DISK}.bak.$(date +%s)" 2>/dev/null || true
cp "$ROUTES_JSON" "${ROUTES_JSON}.bak.$(date +%s)"

echo "[2/5] Restore disk file from verified-good backup"
cp "$GOOD" "$DISK"

echo "[3/5] Register staging in .routes.json (strip generated header)"
python3 - "$ROUTES_JSON" "$GOOD" <<'PY'
import json, sys
routes_path, backup_path = sys.argv[1], sys.argv[2]
with open(routes_path) as f:
    routes = json.load(f)
with open(backup_path) as f:
    raw = f.read()
# Strip the "CODE GENERATED BY SPACE TOOLS" header line
lines = raw.split("\n", 1)
code = lines[1] if lines[0].startswith("// CODE GENERATED") else raw
entry = {"path": "/tinyworld-staging", "type": "page", "code": code, "public": False, "meta": None}
routes = [r for r in routes if r.get("path") != "/tinyworld-staging"]
routes.append(entry)
with open(routes_path, "w") as f:
    json.dump(routes, f)
print(f"  registered staging: {len(code)} chars of route code, {len(routes)} total routes")
PY

echo "[4/5] Build"
cd /__substrate/space && bun run build 2>&1 | tail -3

echo "[5/5] Restart zo-space"
supervisorctl -c /etc/zo/supervisor.conf restart zo-space

echo "DONE — staging restored to disk + .routes.json + rebuilt + restarted."
echo "Verify: curl -s http://localhost:3099/tinyworld-staging?nodeLat=40.7711&nodeLon=-73.9585"
