#!/usr/bin/env bash
# Reboot-recovery for the SHARED /api/tinyworld-capture + /api/tinyworld-infer
# routes — the MERGE-AT-MOST pipeline (supersedes reapply-capture.sh, whose
# backup would resurrect the BANNED destructive scan-replace tier).
#
# PRINCIPLE (locked 2026-07-01, Greene St incident): Replace is banned; merge at
# most. GPS only NOMINATES a merge candidate at capture time
# (merge_candidate_world_id); at infer time merge_capture_into_world.py runs a
# joint COLMAP co-registration gate ("geometry decides") and only merges into
# the old world when both scans share real geometry (prior payload backed up
# first). Otherwise the capture mints a SEPARATE world. No code path may ever
# blind-overwrite an existing world by GPS proximity alone.
#
# WHY this exists: these are "CODE GENERATED BY SPACE TOOLS" routes. A container
# reboot / space sync re-materializes the disk files FROM .routes.json; if that
# store holds stale code the disk edits are wiped (happened 2026-07-01T15:57).
# This script restores BOTH the disk files and the .routes.json entries from
# verified-good backups, then restarts.
#
# WHEN to run: after a reboot, if a capture near your own world reports
# "will overwrite it in place" (old replace tier resurrected) or stamps
# world_id at capture time instead of merge_candidate_world_id.
#
# Idempotent: restoring code that already matches is a no-op + restart.
set -euo pipefail

BK="/home/workspace/project-tinyworld/.route-backups"
GOOD_CAPTURE="$BK/api-tinyworld-capture-20260701T200100Z-merge-nominate.ts"
GOOD_INFER="$BK/api-tinyworld-infer-20260702T171239Z-notify.ts"
GOOD_CAPTURE_PAGE="$BK/tinyworld-capture-page-20260702T171239Z-coach45s.tsx"
DISK_CAPTURE="/__substrate/space/routes/api/api-tinyworld-capture.ts"
DISK_INFER="/__substrate/space/routes/api/api-tinyworld-infer.ts"
DISK_CAPTURE_PAGE="/__substrate/space/routes/pages/tinyworld-capture.tsx"
ROUTES_JSON="/__substrate/space/.routes.json"

for f in "$GOOD_CAPTURE" "$GOOD_INFER" "$GOOD_CAPTURE_PAGE" "$ROUTES_JSON"; do
  [ -f "$f" ] || { echo "FATAL: missing $f"; exit 1; }
done

echo "[1/5] Back up current disk files + .routes.json"
NOW=$(date +%s)
cp "$DISK_CAPTURE" "${DISK_CAPTURE}.bak.$NOW" 2>/dev/null || true
cp "$DISK_INFER" "${DISK_INFER}.bak.$NOW" 2>/dev/null || true
cp "$DISK_CAPTURE_PAGE" "${DISK_CAPTURE_PAGE}.bak.$NOW" 2>/dev/null || true
cp "$ROUTES_JSON" "${ROUTES_JSON}.bak.$NOW"

echo "[2/5] Restore disk files from verified-good backups"
cp "$GOOD_CAPTURE" "$DISK_CAPTURE"
cp "$GOOD_INFER" "$DISK_INFER"
cp "$GOOD_CAPTURE_PAGE" "$DISK_CAPTURE_PAGE"

echo "[3/5] Verify merge-pipeline markers on disk"
cap_markers=(
  "const MERGE_NOMINATE_RADIUS_M = 50"
  "ADD COLUMN merge_candidate_world_id"
  "let mergeCandidateId"
  "shared geometry decides at infer"
)
inf_markers=(
  "merge_capture_into_world.py"
  "runMergeAttempt"
  "ADD COLUMN merge_decision"
  "minting separate world"
  # 2026-07-02 reliability layer: boot sweep + live-worker retry + timeouts
  "sweepOrphanedInferring"
  "liveWorkers"
  "INFER_TIMEOUT_MS"
  # 2026-07-02 done/fail Telegram notification via /zo/ask
  "notifyScanResult"
)
# Capture PAGE markers: live coaching + 45s scan bank (30s is a stale revert).
page_markers=(
  "const SCAN_BANK_START_S = 45"
  "COACH_ROT_DEG_S"
  "coachTick"
)
for m in "${cap_markers[@]}"; do
  grep -qF "$m" "$DISK_CAPTURE" || { echo "FATAL: capture marker missing: $m"; exit 1; }
done
for m in "${inf_markers[@]}"; do
  grep -qF "$m" "$DISK_INFER" || { echo "FATAL: infer marker missing: $m"; exit 1; }
done
for m in "${page_markers[@]}"; do
  grep -qF "$m" "$DISK_CAPTURE_PAGE" || { echo "FATAL: capture page marker missing: $m"; exit 1; }
done
# The banned tier must NOT be present anywhere.
if grep -qF "replaceWorldId" "$DISK_CAPTURE"; then
  echo "FATAL: banned replace tier present in capture route"; exit 1
fi
echo "      all merge markers present; replace tier absent."

echo "[4/5] Register routes in .routes.json (strip generated header)"
python3 - "$ROUTES_JSON" "$GOOD_CAPTURE" "$GOOD_INFER" "$GOOD_CAPTURE_PAGE" <<'PY'
import json, sys
routes_path, cap_path, inf_path, page_path = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
def code_of(p):
    raw = open(p).read()
    first, _, rest = raw.partition("\n")
    return rest if first.startswith("// CODE GENERATED") else raw
want = {
    "/api/tinyworld-capture": code_of(cap_path),
    "/api/tinyworld-infer": code_of(inf_path),
    "/tinyworld/capture": code_of(page_path),
}
routes = json.load(open(routes_path))
seen = set()
for r in routes:
    if r.get("path") in want:
        r["code"] = want[r["path"]]
        seen.add(r["path"])
missing = set(want) - seen
if missing:
    print(f"FATAL: no .routes.json entry for {missing}"); sys.exit(1)
json.dump(routes, open(routes_path, "w"))
for p in seen:
    print(f"  registered {p}: {len(want[p])} chars")
PY

echo "[5/5] Rebuild + restart zo-space server"
(cd /__substrate/space && bun run build >/dev/null 2>&1) || echo "WARN: vite build failed — pages may serve stale bundle"
supervisorctl -c /etc/zo/supervisor.conf restart zo-space || \
  supervisorctl -s http://127.0.0.1:29001 restart zo-space || \
  supervisorctl restart zo-space

echo
echo "Verify: curl -s http://localhost:3099/api/tinyworld-capture returns JSON,"
echo "        POST response near an owned world says 'GPS nominated a merge',"
echo "        and PRAGMA table_info(pending_captures) shows merge_candidate_world_id."
echo "DONE — merge-at-most capture+infer routes restored to disk + .routes.json + restarted."
